# Generated by Django 5.2.4 on 2025-07-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermetadata',
            table='users_metadata',
        ),
    ]
